require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe']
  Max: 35

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false
