version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run:
          name: "Install the dependencies"
          command: bundle install --jobs=4 --retry=3
          environment:
            PUPPET_GEM_VERSION: "~> 7.6.1"
      - run:
          name: "Run the specs"
          command: bundle exec rake spec
